### ISSUE TITLE
Please add this name to the developer list

### ISSUE THREAD

**Issue by untsamphan** [kytulendu/CW141#1]
วิชัย ปฏิภาภรณ์ (Wichai Patipaporn)

Back then, he was in the same class at CU as those guys (CP12, I guess). He wrote a big part of the code w/o letting them mention his name in the book. I (CP14) happened to be there at the time.

He also wrote two other famous software, ThaiTip and vthai.

**Comment by kytulendu** [comment]
Thank you. I'll add the name to the readme file.
